export enum ECategoryActions {
  GET_LIST_CATEGORY = 'GET_LIST_CATEGORY',
  SET_LIST_CATEGORY = 'SET_LIST_CATEGORY',
  GET_LIST_FORUMS_CATEGORY = 'GET_LIST_FORUMS_CATEGORY',
  SET_LIST_FORUMS_CATEGORY = 'SET_LIST_FORUMS_CATEGORY'
}
