export enum EPaginateActions {
  PAGINATE_NEWS = 'PAGINATE_NEWS',
  PAGINATE_TRENDING = 'PAGINATE_TRENDING',
  PAGINATE_HIGHLIGHT = 'PAGINATE_HIGHLIGHT',
  PAGINATE_ALL_PAGE = 'PAGINATE_ALL_PAGE',
  PAGINATE_GAMES = 'PAGINATE_GAMES',
  PAGINATE_REVIEWS = 'PAGINATE_REVIEWS',
  PAGINATE_USER_POSTS = 'PAGINATE_USER_POSTS'
}
