export enum EForumActions {
  FETCH_NEW_FORUMS = 'FETCH_NEW_FORUMS',
  FETCH_FORUMS_BY_CATEGORY = 'FETCH_FORUMS_BY_CATEGORY',
  FETCH_MORE_FORUMS_BY_CATEGORY = 'FETCH_MORE_FORUMS_BY_CATEGORY',
  FETCH_USER_FORUMS = 'FETCH_USER_FORUMS',
  CREATE_FORUMS = 'CREATE_FORUMS',
  GET_COMMENTS = 'GET_COMMENTS',
  COMMENT = 'COMMENT'
}
