export enum EPostActions {
  FETCH_NEW_POSTS = 'FETCH_NEW_POSTS',
  FETCH_TOP_TRENDING = 'FETCH_TOP_TRENDING',
  FETCH_RANDOM_POSTS = 'FETCH_RANDOM_POSTS',
  SHOW_POST = 'SHOW_POST',
  CREATE_POST = 'CREATE_POST'
}
